[[constraint]]
  name = "gopkg.in/src-d/go-mysql-server.v0"
  revision = "bafb29ae6359a6ad757b64751f3f8a5c807adc70"

[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.3.0"

[[constraint]]
  name = "github.com/hashicorp/golang-lru"
  version = "0.5.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  source = "github.com/src-d/go-git"
  revision = "5cc316baa64287c7e56cb7372a5046c30fd955c1"

[[constraint]]
  name = "gopkg.in/src-d/go-git-fixtures.v3"
  version = "3.0.0"

[[override]]
  name = "golang.org/x/sys"
  source = "github.com/golang/sys"
  revision = "f0d5e33068cb57c22a181f5df0ffda885309eb5a"

[[override]]
  name = "golang.org/x/crypto"
  source = "github.com/golang/crypto"

[[override]]
  name = "golang.org/x/text"
  source = "github.com/golang/text"

[[override]]
  name = "golang.org/x/net"
  source = "github.com/golang/net"

[[override]]
  name = "google.golang.org/grpc"
  version = "1.14.0"

[[override]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  name = "gopkg.in/src-d/enry.v1"
  version = "1.6.5"

[[constraint]]
  name = "gopkg.in/bblfsh/client-go.v2"
  version = "2.8.4"

[[constraint]]
  name = "gopkg.in/bblfsh/sdk.v1"
  version = "1.16.0"

[[constraint]]
  name = "github.com/uber/jaeger-client-go"
  version = "^2.7.0"

[[override]]
  name = "github.com/pilosa/pilosa"
  version = "1.1.0"

[[override]]
  name = "github.com/pilosa/go-pilosa"
  version = "0.10.0"

[[override]]
  name = "github.com/moovweb/rubex"
  branch = "go1"
